substitutions:
  name: total-count
  external_components_source: github://syssi/esphome-total-count@main

esphome:
  name: ${name}
  platform: ESP32
  board: esp-wrover-kit

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
ota:
logger:

total_count:
  - id: total_count0
    binary_sensor_id: barrier0
    restore: true
    min_save_interval: 300s
    initial_value: 0
    step: 1
  - id: total_count1
    binary_sensor_id: barrier1
    restore: true
    min_save_interval: 300s
    initial_value: 0
    step: 1

binary_sensor:
  - platform: gpio
    pin: GPIO32
    name: "${name} light barrier 0"
    id: barrier0
    filters:
      - delayed_on: 20ms
  - platform: gpio
    pin: GPIO33
    name: "${name} light barrier 1"
    id: barrier1
    filters:
      - delayed_on: 20ms

sensor:
  - platform: total_count
    total_count_id: total_count0
    total_count:
      name: "${name} total count 0"
  - platform: total_count
    total_count_id: total_count1
    total_count:
      name: "${name} total count 1"

number:
  - platform: total_count
    total_count_id: total_count0
    total_count:
      name: "${name} total count 0"
  - platform: total_count
    total_count_id: total_count1
    total_count:
      name: "${name} total count 1"

button:
  - platform: total_count
    total_count_id: total_count0
    reset_counter:
      name: "${name} reset counter 0"
  - platform: total_count
    total_count_id: total_count1
    reset_counter:
      name: "${name} reset counter 1"
