substitutions:
  name: total-count
  external_components_source: github://syssi/esphome-total-count@main

esphome:
  name: ${name}
  min_version: 2024.6.0

esp8266:
  board: d1_mini

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome

logger:
  level: DEBUG

api:

total_count:
  binary_sensor_id: barrier
  restore: true
  min_save_interval: 300s
  initial_value: 0
  step: 1

binary_sensor:
  - platform: gpio
    pin: GPIO32
    name: "${name} light barrier"
    id: barrier
    filters:
      - delayed_on: 20ms

sensor:
  - platform: total_count
    total_count:
      name: "${name} total count"

number:
  - platform: total_count
    total_count:
      name: "${name} total count"

button:
  - platform: total_count
    reset_counter:
      name: "${name} reset counter"
